name: WorldTextPlugin
version: 1.0
main: Main
api-version: 1.19
commands:
  christmascard:
    description: A command to write a lovely christmas card in minecraft
    usage: /christmascard
description: A plugin that generates christmas cards in the Minecraft world.
author: Rasmus Wittrock
